# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_auto_20160507_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u044d\u0433')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441\u044b')),
            ],
            options={
                'verbose_name': '\u0422\u044d\u0433',
                'verbose_name_plural': '\u0422\u0435\u0433\u0438',
            },
        ),
    ]
