# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.AddField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(to='ask.Question', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441\u044b'),
        ),
    ]
