# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20160507_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_tags',
            field=models.ManyToManyField(to='ask.Tag', verbose_name='\u0422\u044d\u0433\u0438'),
        ),
    ]
