# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0007_auto_20160508_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_like',
            name='users',
        ),
        migrations.AddField(
            model_name='question',
            name='Liked_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Question_Like',
        ),
    ]
