# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0009_question_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Liked_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
