# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='some text', verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
