# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0012_auto_20160515_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_answ',
            field=models.IntegerField(default=0),
        ),
    ]
