# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_question_num_answ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_answ',
        ),
    ]
