# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0014_remove_question_num_answ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answ', to='ask.Question'),
        ),
    ]
