# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0015_auto_20160515_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='avatar_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0438\u043a'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='authors',
        ),
        migrations.AddField(
            model_name='question',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_question', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440\u044b'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
