# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0016_auto_20160515_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='\u041d\u0438\u043a'),
        ),
    ]
