# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0017_auto_20160515_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/media.images/'),
        ),
    ]
