# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0019_auto_20160522_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL \u0430\u0432\u0430\u0442\u0430\u0440\u043a\u0438?'),
        ),
    ]
