# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0023_auto_20160522_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='DisLiked_users',
            field=models.ManyToManyField(related_name='DisLiked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='Liked_users',
            field=models.ManyToManyField(related_name='Liked_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
