# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0024_auto_20160522_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='DisLiked_users',
            field=models.ManyToManyField(null=True, related_name='DisLiked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='Liked_users',
            field=models.ManyToManyField(null=True, related_name='Liked_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
