# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0026_auto_20160524_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
