# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0027_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_answers', to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440\u044b'),
        ),
    ]
